language: node_js
node_js:
  - "lts/*"

before_script:
  - npm install
  - npm install -g gulp-cli codecov

script:
  - npm run test

after_success:
  - npm run typedoc
  - npm pack
  - codecov -f coverage/*.json

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GITHUB_TOKEN

  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "samsung-tv-control-*.tgz"
    skip_cleanup: true
    on:
      tags: true

  - provider: npm
    skip_cleanup: true
    email: "toxblh@gmail.com"
    api_key: $NPM_TOKEN
    on:
      tags: true
